### ISSUE TITLE
是否可以直接跳转至打开的搜索页面

### ISSUE THREAD

**Issue by flyingicedragon** [garywill/BigSearch#20]
现在的几个选项都是调整新标签位置，希望可以添加直接跳转至新标签的功能和选项。

**Comment by garywill** [comment]
发现有几个问题

如果打开新标签后，直接让浏览器切换到新标签，
我们的界面会失去焦点。这样vem模式就不能继续接收键盘事件了

而且Chrome还会马上关闭我们的工具栏按钮弹出界面
（Firefox虽然不关闭）

所以看来，好像你提的这个需求，只有在以下情况有用：
1。 Firefox，使用工具栏弹出，或侧边栏，且不用vem
2。 Chrome，使用侧边栏，且不用vem

而至于使用单独标签装载我们的搜索界面的，好像应该也不会需要这个需求

这样的话，你觉得呢？还有必要搞这个马上跳转至的功能吗？

**Comment by flyingicedragon** [comment]
> 发现有几个问题
> 
> 如果打开新标签后，直接让浏览器切换到新标签， 我们的界面会失去焦点。这样vem模式就不能继续接收键盘事件了
> 
> 而且Chrome还会马上关闭我们的工具栏按钮弹出界面 （Firefox虽然不关闭）
> 
> 所以看来，好像你提的这个需求，只有在以下情况有用： 1。 Firefox，使用工具栏弹出，或侧边栏，且不用vem 2。 Chrome，使用侧边栏，且不用vem
> 
> 而至于使用单独标签装载我们的搜索界面的，好像应该也不会需要这个需求
> 
> 这样的话，你觉得呢？还有必要搞这个马上跳转至的功能吗？

在我的使用习惯下还是有价值的。我一般不会一次性打开多个搜索页面。而是在没有找到满意结果的情况下才会换一个搜索工具。BigSearch 目前会保留最近的搜索内容，配合键盘快捷键唤出弹出界面哪怕需要重新 `Shift+Enter` 进入 vem 模式也还是很有效率的。

**Comment by garywill** [comment]
好的。不过可能要再等等，这几天实在太忙了，放假都没时间。。。。
关键代码在这个位置
https://github.com/garywill/BigSearch/blob/5c3a32ee360873fbc7f5287dae3061ad1ec0635b/src/engine_handle.js#L395

**Comment by flyingicedragon** [comment]
@garywill 好的，辛苦了。我这前端知识都是为了写爬虫学的。写写搜索引擎那部分还行，具体的逻辑代码就不献丑了。

**Comment by garywill** [comment]
新版已完成
