### ISSUE TITLE
在 Chrome 内核浏览器中窗口显示过大

### ISSUE THREAD

**Issue by jdjxk** [garywill/BigSearch#24]
### 在 Chrome 内核浏览器中窗口显示过大，右边和下方出现滚动条

![image](https://github.com/user-attachments/assets/d44b15dd-e0fb-4c28-a108-9f2bbcb03ec4)

### 在 Firefox 内核浏览器中无此问题

![image](https://github.com/user-attachments/assets/11d655b9-4f93-47fb-abc1-8b9e6d33b8f4)

**Comment by garywill** [comment]
你的chrome版本是多少？
有没有在系统桌面那里设置过缩放？或浏览器有没有设置过缩放等级？

**Comment by jdjxk** [comment]
浏览器全局缩放修改到90%或以下才能恢复正常，100%不行。系统缩放等级不管怎么调整都一样。
浏览器版本126-128都不行，好像是从Chrome某一个版本开始出现这个问题。

**Comment by jdjxk** [comment]
更早的版本还没时间排查，这个现象有几个月了，之前一直没反馈

**Comment by jdjxk** [comment]
已排查完毕，Chrome 120 及以下版本显示正常，121 及以上版本出现此问题，疑似 Refresh 2023 新 UI 导致，请帮助修复，谢谢！

**Comment by garywill** [comment]
试试在弹出界面中，打开右键菜单，点检查，把<body>的宽改为780px，看还有滚动条吗

**Comment by jdjxk** [comment]
宽改780px可以恢复正常

**Comment by jdjxk** [comment]
3.6.8 问题解决，感谢！
