### ISSUE TITLE
Add search.brave.com to Engines Claiming No-Tracking

### ISSUE THREAD

**Issue by cachius** [garywill/BigSearch#27]
The browser vendor [Brave also operates a search engine](https://brave.com/search/). Please include it under Engines Claiming No-Tracking.

**Comment by cachius** [comment]
Thank you! Check this out, @brave!

Where does the extension get its search engine list from?
I expected a commit but found none, that's why I wonder.

**Comment by garywill** [comment]
Usually I release to addon store, then Github gets update late. Because I'm the only one maintaining the code currently, people are not participating, so I feel a bit unmotivated to push code to Github.

The extension gets engine list from its `enginedata.js` file
