### ISSUE TITLE
Bad UI on Ubuntu Chrome x64

### ISSUE THREAD

**Issue by Enissay** [garywill/BigSearch#5]
Hi Gary,

Congrats for putting this amazing extension finally on the play store.

I just installed it in Ubuntu, and I noticed a wrong UI display, so basically you need to scroll left/right to see the whole content of the pop-up:

![ext1](https://user-images.githubusercontent.com/794673/150691797-87e1fa1f-4e2e-46c7-9365-883a591cb944.png)

![ext2](https://user-images.githubusercontent.com/794673/150691802-3263f35f-8537-441f-87b6-cd698eeb88a2.png)

PS: for the sake of completeness, I tested the FireFox version even though I don't use it, and it is working fine there (the UI part at least)

Coridally,

**Comment by garywill** [comment]
Hi ! Thank you for feedback!
In your screenshot, everything in the popup looks zoomed (you could compare the text and block size in Firefox and in Chrome). Did you acciddently zoomed it?
I didn't reproduce this issue on Chromium 95 and 97. What Chrome version are you using?

**Comment by Enissay** [comment]
Hmm, good point.
I am using `Version 97.0.4692.71 (Official Build) (64-bit)`... Checkout these comparative gifs:
- Chrome
![ch](https://user-images.githubusercontent.com/794673/150788831-2465481e-6b88-435c-9463-21640b2d9738.gif)

- Firefox
![ff](https://user-images.githubusercontent.com/794673/150788865-765a8f61-db30-4638-a38e-e981b0cdd597.gif)

**Comment by Enissay** [comment]
Okay, I just recalled that since I have a large 4K screen, fonts are too small to read, so I changed the default zoom in chrome to 125%. resetting it back to 100% solves the issue.

However, it is worth mentioning that none of my other 30+ extensions have any UI impact like this one... But, in anycase, that horizontal scrolling doesnt bother me that much, I can live with it :-)

![zoom](https://user-images.githubusercontent.com/794673/150789474-63d2e8f0-59c9-4a42-913a-2ce52942a56e.png)

**Comment by garywill** [comment]
That's also a deficiency of our addon. It is currently dumb static layout.
It needs a responsive layout, which I think will solve that. (Really hope any one help me with my poor css)

A workaround: open the UI in a tab
```
chrome-extension://ojcnjeigmgjaiolalpapfnmmhdmpjhfb/addon-popup.html
```

> none of my other 30+ extensions have any UI impact like this one

I think they are zoomed, but didn't reach the max size of allowed size.
The max size of a popup is 800x600. Our addon has already been using that.

**Comment by Enissay** [comment]
> Really hope any one help me with my poor css

Sadly not me, It would be a good idea to add a new readme section so anyone with the required skills can easily reach out to you
Oh, if you can also add a Table Of Content to make it easy to navigate

> I think they are zoomed, but didn't reach the max size of allowed size.
> The max size of a popup is 800x600. Our addon has already been using that.

Correct, none of them is this large.
